require.config({
    paths:{
        jquery:'../jq/jquery-3.2.1.min',
        cart:'./lib/cart',
        cookie:'../jq/jquery.cookie'
    }
})
require(['jquery','cart'],function($,catr){
    catr.init();
})